from typing import Any, Protocol
from collections.abc import Callable

class CommandError(Exception): pass
class ReactorTimer(Protocol):
    pass

class Reactor(Protocol):
    NEVER: float
    NOW: float
    def register_timer(self, Callable, waketime=float) -> ReactorTimer: ...
    def update_timer(self, timer_handler: ReactorTimer, waketime: float) -> None: ...

class Printer(Protocol):
    command_error: type[CommandError]
    objects: dict[str, Any]
    def get_reactor(self) -> Reactor: ...
    def lookup_object(self, name: str, default: Any = ...) -> Any: ...
    def lookup_objects(self, module: str = ...) -> list[tuple[str, Any]]: ...
    def load_object(self, config: str, section: str, default: Any = ...) -> Any: ...
    def register_event_handler(self, event: str, handler: Any) -> None: ...

class GCode(Protocol):
    def register_command(self, cmd: str, func: Callable[[GCodeCommand], None], when_not_ready:bool = ..., desc:str=...) -> None: ...
    def run_script(self, scriptstr) -> None: ...
    def respond_info(self, msg: str) -> None: ...
    def register_mux_command(self, cmd: str, key: str, value: str, func: Callable, desc: str = ...) -> None: ...

class GCodeCommand(Protocol):
    error: Exception
    def get(self, name) -> str: ...

class KlipperHost(Protocol):
    printer: Printer
    gcode: GCode
    # Add 'reactor' or 'eventtime' if you use them
