from _typeshed import Incomplete

# fan.py:
class Fan:
    printer: Incomplete
    last_fan_value: float
    max_power: Incomplete
    kick_start_time: Incomplete
    off_below: Incomplete
    mcu_fan: Incomplete
    enable_pin: Incomplete
    gcrq: Incomplete
    tachometer: Incomplete
    def __init__(self, config, default_shutdown_speed: float = 0.0) -> None: ...
    def get_mcu(self): ...
    def set_speed(self, value, print_time=None) -> None: ...
    def set_speed_from_command(self, value) -> None: ...
    def get_status(self, eventtime): ...

class FanTachometer:
    ppr: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...

class PrinterFan:
    fan: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...
    def cmd_M106(self, gcmd) -> None: ...
    def cmd_M107(self, gcmd) -> None: ...

# Heaters.py:
KELVIN_TO_CELSIUS: float
MAX_HEAT_TIME: float
AMBIENT_TEMP: float
PID_PARAM_BASE: float
MAX_MAINTHREAD_TIME: float
QUELL_STALE_TIME: float

class Heater:
    printer: Incomplete
    name: Incomplete
    short_name: Incomplete
    sensor: Incomplete
    min_temp: Incomplete
    max_temp: Incomplete
    pwm_delay: Incomplete
    min_extrude_temp: Incomplete
    can_extrude: Incomplete
    max_power: Incomplete
    smooth_time: Incomplete
    inv_smooth_time: Incomplete
    verify_mainthread_time: float
    lock: Incomplete
    last_temp: float
    last_temp_time: float
    next_pwm_time: float
    last_pwm_value: float
    control: Incomplete
    mcu_pwm: Incomplete
    def __init__(self, config, sensor) -> None: ...
    def set_pwm(self, read_time, value) -> None: ...
    def temperature_callback(self, read_time, temp) -> None: ...
    def get_name(self): ...
    def get_pwm_delay(self): ...
    def get_max_power(self): ...
    def get_smooth_time(self): ...
    target_temp: Incomplete
    def set_temp(self, degrees) -> None: ...
    def get_temp(self, eventtime): ...
    def check_busy(self, eventtime): ...
    def set_control(self, control): ...
    def alter_target(self, target_temp) -> None: ...
    def stats(self, eventtime): ...
    def get_status(self, eventtime): ...
    cmd_SET_HEATER_TEMPERATURE_help: str
    def cmd_SET_HEATER_TEMPERATURE(self, gcmd) -> None: ...

class ControlBangBang:
    heater: Incomplete
    heater_max_power: Incomplete
    max_delta: Incomplete
    heating: bool
    def __init__(self, heater, config) -> None: ...
    def temperature_update(self, read_time, temp, target_temp) -> None: ...
    def check_busy(self, eventtime, smoothed_temp, target_temp): ...

PID_SETTLE_DELTA: float
PID_SETTLE_SLOPE: float

class ControlPID:
    heater: Incomplete
    heater_max_power: Incomplete
    Kp: Incomplete
    Ki: Incomplete
    Kd: Incomplete
    min_deriv_time: Incomplete
    temp_integ_max: float
    prev_temp: Incomplete
    prev_temp_time: float
    prev_temp_deriv: float
    prev_temp_integ: float
    def __init__(self, heater, config) -> None: ...
    def temperature_update(self, read_time, temp, target_temp) -> None: ...
    def check_busy(self, eventtime, smoothed_temp, target_temp): ...

class PrinterHeaters:
    printer: Incomplete
    sensor_factories: Incomplete
    heaters: Incomplete
    gcode_id_to_sensor: Incomplete
    available_heaters: Incomplete
    available_sensors: Incomplete
    available_monitors: Incomplete
    has_started: bool
    def __init__(self, config) -> None: ...
    have_load_sensors: bool
    def load_config(self, config) -> None: ...
    def add_sensor_factory(self, sensor_type, sensor_factory) -> None: ...
    def setup_heater(self, config, gcode_id=None): ...
    def get_all_heaters(self): ...
    def lookup_heater(self, heater_name): ...
    def setup_sensor(self, config): ...
    def register_sensor(self, config, psensor, gcode_id=None) -> None: ...
    def register_monitor(self, config) -> None: ...
    def get_status(self, eventtime): ...
    def turn_off_all_heaters(self, print_time: float = 0.0) -> None: ...
    cmd_TURN_OFF_HEATERS_help: str
    def cmd_TURN_OFF_HEATERS(self, gcmd) -> None: ...
    def cmd_M105(self, gcmd) -> None: ...
    def set_temperature(self, heater, temp, wait: bool = False) -> None: ...
    cmd_TEMPERATURE_WAIT_help: str
    def cmd_TEMPERATURE_WAIT(self, gcmd) -> None: ...
